name: pr-build

on:
  pull_request:
    types:
      - opened
    branches: [beta, main, nightly]

jobs:
  dotnet-build:
    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '6.0.x' ]
        os: [ubuntu-latest ]
    uses: rain-dev/git-actions/.github/workflows/dotnet-build.yml@main
    with:
      project-path: ./src/AutoFixture.Helper.sln
      dotnet-version: ${{ matrix.dotnet-version }}
      os: ${{ matrix.os }}
  dotnet-publish:
    needs: dotnet-build
    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '6.0.x' ]
        os: [ubuntu-latest]
    uses: rain-dev/git-actions/.github/workflows/dotnet-publish.yml@main
    with:
      project-path: ./src/AutoFixture.Helper.sln
      dotnet-version: ${{ matrix.dotnet-version }}
      os: ${{ matrix.os }}
      package-name: 'AutoFixture.Helper'
    
    
    
    